AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless Polly Page

Parameters:
  ApplicationName:
    Type: String
    Default: 'ServerlessPollyPage'
  PollyLanguageCode:
    Type: String
    Default: 'ja-JP'
  PollyVoiceId:
    Type: String
    Default: 'Takumi'
  FrontPageApiStageName:
    Type: String
    Default: 'ProdStage'

Resources:
  FrontPageApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServerlessPollyPageApi
      EndpointConfiguration: REGIONAL
      StageName: !Ref FrontPageApiStageName
  FileBucket:
    Type: AWS::S3::Bucket
  FrontPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ServerlessPollyPageFrontFunction
      CodeUri: bin/
      Handler: main
      MemorySize: 256
      Runtime: go1.x
      Description: 'Test Front Function'
      Policies:
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          API_PATH: !Join [ '', [ '/', !Ref FrontPageApiStageName, '/api'] ]
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/'
            Method: get
            RestApiId: !Ref FrontPageApi
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ServerlessPollyPageApiFunction
      CodeUri: api/bin/
      Handler: main
      MemorySize: 256
      Runtime: go1.x
      Description: 'Test Polly Function'
      Policies:
      - S3CrudPolicy:
          BucketName: !Ref FileBucket
      - Statement:
        - Sid: PollySynthesizeSpeechPolicy
          Effect: Allow
          Action:
          - polly:SynthesizeSpeech
          Resource: '*'
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          BUCKET_NAME: !Ref 'FileBucket'
          VOICE_ID: !Ref 'PollyVoiceId'
          LANGUAGE_CODE: !Ref 'PollyLanguageCode'
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/api'
            Method: post
            RestApiId: !Ref FrontPageApi

Outputs:
  APIURI:
    Description: "URI"
    Value: !Join [ '', [ 'https://', !Ref FrontPageApi, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref FrontPageApiStageName,'/'] ]
